[package]
name = "xwt-example-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cfg-if = "1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
xwt-example-server-native = { version = "0.1", path = "../server-native", default-features = false }
