[package]
name = "xwt"
version = "0.11.0"
edition = "2021"
resolver = "2"
license = "MIT"
description = """
A common WebTransport interface for browser and native.
Write once, run anywhere. Originally intended for use with bevy.
"""
repository = "https://github.com/MOZGIII/xwt"

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "i686-unknown-linux-gnu",
  "i686-pc-windows-msvc",
  "wasm32-unknown-unknown",
]

[dependencies]
xwt-core = { version = "0.3", path = "../xwt-core", default-features = false }
