[package]
name = "xwt-wtransport"
version = "0.2.5"
edition = "2021"
resolver = "2"
license = "MIT"
description = """
An implementation of the xwt that runs natively via wtransport crate.
"""
repository = "https://github.com/MOZGIII/xwt"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
xwt-core = { version = "0.2", path = "../xwt-core", default-features = false }

wtransport = { version = "0.1.10" }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
xwt-tests = { version = "0.4.1", path = "../xwt-tests" }
xwt-test-assets = { version = "0.1", path = "../xwt-test-assets" }

anyhow = "1"
tokio = { version = "1", features = ["macros"] }
color-eyre = "0.6"
tracing-subscriber = "0.3"
