[package]
name = "xwt-example-server-native"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(not(target_family = "wasm"))'.dependencies]
# Shared server code for the example.
xwt-example-server-shared = { version = "0.1", path = "../server-shared", default-features = false }

# Core xwt primitives and driver.
xwt-cert-fingerprint = { version = "0.1", path = "../../../crates/xwt-cert-fingerprint", default-features = false }
xwt-core = { version = "0.3", path = "../../../crates/xwt-core", default-features = false }
xwt-wtransport = { version = "0.6", path = "../../../crates/xwt-wtransport", default-features = false }

# The dependency specific to this being an xwt example that is designed to
# work with an xwt test server.
xwt-test-assets = { version = "0.1", path = "../../../crates/xwt-test-assets", default-features = false }

# The rest of the dependencies.
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wtransport = { version = "0.1.12", default-features = false, features = ["dangerous-configuration", "self-signed"] }
