[target.'cfg(all())']
rustflags = [
  "--cfg=web_sys_unstable_apis",

  "-Dunsafe_code",
  "-Wclippy::all",
  "-Wclippy::cargo",
  "-Wmissing_docs",
  "-Wclippy::missing_docs_in_private_items",
  "-Wclippy::clone_on_ref_ptr",
  "-Wclippy::await_holding_lock",
  # A few exceptions.
  "-Aclippy::multiple-crate-versions",
  "-Aclippy::derive-partial-eq-without-eq",
  "-Aclippy::cargo-common-metadata",
]

[target.wasm32-unknown-unknown]
runner = "cargo-advrunner"
